# This workflow tests PRs by running ng build, npm audit and ng lint

name: Build, lint and check for vulnerabilities

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events for the master branch
  pull_request:
    branches: [ master ]
    # Run validation on code files, json and projects/
    paths:
      - '**.json'
      - 'projects/**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "validate_pr"
  validate_pr:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm install

      # Build Code
      - name: Run ng build
        run: node_modules/@angular/cli/bin/ng build --configuration production

      # Lint Code
      - name: Run ng lint
        run: node_modules/@angular/cli/bin/ng lint

      # Run npm audit
      - name: Run npm audit
        run: npm audit --omit dev
